import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { prisma } from "@/lib/prisma";
import type { VetReadyReport } from "@/app/api/pets/[id]/vet-report/route";
import { VetReportLinkViewTracker } from "@/components/vet-report/vet-report-link-view-tracker";

interface Props {
  params: Promise<{ reportId: string }>;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { reportId } = await params;
  const record = await prisma.vetReport.findUnique({
    where: { id: reportId },
    select: { reportData: true },
  });
  if (!record) return { title: "Vet Report | FursBliss", robots: { index: false, follow: false } };
  const report = record.reportData as unknown as VetReadyReport;
  return {
    title: `${report.pet.name}'s Health Summary | FursBliss`,
    description: `30-day health summary for ${report.pet.name} (${report.pet.breed}, ${report.pet.age}). ${report.concerns.length} concern(s) flagged.`,
    // Private share link — do not index
    robots: { index: false, follow: false },
  };
}

function SeverityDot({ severity }: { severity: "high" | "medium" | "low" }) {
  const colors = { high: "bg-red-500", medium: "bg-amber-400", low: "bg-slate-400" };
  return <span className={`inline-block w-2 h-2 rounded-full shrink-0 mt-1 ${colors[severity]}`} />;
}

function TrendArrow({ trend }: { trend: "improving" | "declining" | "stable" }) {
  if (trend === "improving") return <span className="text-green-600 font-medium">↑</span>;
  if (trend === "declining") return <span className="text-red-600 font-medium">↓</span>;
  return <span className="text-slate-400">→</span>;
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-xs font-semibold uppercase tracking-widest text-slate-500 mb-2 pb-1 border-b">
        {title}
      </h2>
      {children}
    </section>
  );
}

export default async function PublicVetReportPage({ params }: Props) {
  const { reportId } = await params;

  const record = await prisma.vetReport.findUnique({
    where: { id: reportId },
    select: { reportData: true, expiresAt: true, createdAt: true },
  });

  if (!record) notFound();

  if (record.expiresAt < new Date()) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-slate-50 px-4">
        <div className="max-w-md text-center space-y-3">
          <div className="text-4xl">⏰</div>
          <h1 className="text-xl font-semibold text-slate-800">This report link has expired.</h1>
          <p className="text-slate-500 text-sm">
            Shared vet report links are valid for 30 days. The pet owner can generate a new link
            from their FursBliss dashboard.
          </p>
          <a
            href="https://fursbliss.com"
            className="inline-block text-sm text-blue-600 underline"
          >
            fursbliss.com
          </a>
        </div>
      </div>
    );
  }

  const report = record.reportData as unknown as VetReadyReport;
  const generatedDate = new Date(report.generatedAt).toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  return (
    <>
      {/* Client-side pixel tracker — fires VetReport_LinkViewed */}
      <VetReportLinkViewTracker reportId={reportId} petName={report.pet.name} />

      <div className="min-h-screen bg-slate-50 py-8 px-4 print:bg-white print:py-0">
        <div className="max-w-2xl mx-auto space-y-6">

          {/* Banner */}
          <div className="rounded-lg bg-blue-50 border border-blue-200 px-4 py-3 text-sm text-blue-800 flex items-start gap-2">
            <span className="shrink-0 mt-0.5">ℹ</span>
            <span>
              This health summary was generated by{" "}
              <a href="https://fursbliss.com" className="font-semibold underline">
                FursBliss
              </a>{" "}
              for <strong>{report.pet.name}</strong>. It reflects owner-recorded observations and is
              not a veterinary diagnosis.
            </span>
          </div>

          {/* Header card */}
          <div className="rounded-xl bg-white border shadow-sm overflow-hidden">
            <div className="bg-slate-800 px-6 py-4 text-white">
              <div className="flex items-start justify-between gap-4">
                <div>
                  <h1 className="text-xl font-bold">FursBliss Vet-Ready Health Summary</h1>
                  <p className="text-slate-300 text-sm mt-0.5">{report.pet.name}</p>
                </div>
                <div className="text-right text-xs text-slate-400 shrink-0">
                  <div>{report.period.start} — {report.period.end}</div>
                  <div>Generated {generatedDate}</div>
                </div>
              </div>
            </div>

            <div className="px-6 py-5 space-y-5">

              {/* Patient info */}
              <Section title="Patient Information">
                <div className="grid grid-cols-2 gap-x-8 gap-y-1 text-sm">
                  <div><span className="text-slate-500">Name:</span> <span className="font-medium">{report.pet.name}</span></div>
                  <div><span className="text-slate-500">Breed:</span> <span className="font-medium">{report.pet.breed}</span></div>
                  <div><span className="text-slate-500">Age:</span> <span className="font-medium">{report.pet.age}</span></div>
                  <div>
                    <span className="text-slate-500">Weight:</span>{" "}
                    <span className="font-medium">{report.pet.weight.current} lbs</span>
                    {report.pet.weight.thirtyDaysAgo && (
                      <span className="text-slate-400 text-xs ml-1">
                        (was {report.pet.weight.thirtyDaysAgo} lbs 30d ago)
                      </span>
                    )}
                  </div>
                  <div className="col-span-2">
                    <span className="text-slate-500">Tracking period:</span>{" "}
                    <span className="font-medium">{report.period.totalDaysLogged} of 30 days logged</span>
                    <span className="text-slate-400 text-xs ml-1">({report.period.logCompletionRate}% completion)</span>
                  </div>
                </div>
              </Section>

              {/* 30-day trends */}
              <Section title="30-Day Health Trends (scale 1–10, W1 = oldest, W4 = most recent)">
                <div className="overflow-x-auto">
                  <table className="w-full text-sm border-collapse">
                    <thead>
                      <tr className="text-left">
                        <th className="py-1.5 pr-4 text-xs font-medium text-slate-500">Metric</th>
                        <th className="py-1.5 px-2 text-xs font-medium text-slate-500 text-center">W1</th>
                        <th className="py-1.5 px-2 text-xs font-medium text-slate-500 text-center">W2</th>
                        <th className="py-1.5 px-2 text-xs font-medium text-slate-500 text-center">W3</th>
                        <th className="py-1.5 px-2 text-xs font-medium text-slate-500 text-center">W4</th>
                        <th className="py-1.5 px-2 text-xs font-medium text-slate-500 text-center">Avg</th>
                        <th className="py-1.5 pl-2 text-xs font-medium text-slate-500">Trend</th>
                      </tr>
                    </thead>
                    <tbody>
                      {(["energy", "appetite", "mobility", "mood"] as const).map((metric, i) => {
                        const d = report.trends[metric];
                        return (
                          <tr key={metric} className={i % 2 === 0 ? "bg-slate-50" : ""}>
                            <td className="py-1.5 pr-4 font-medium capitalize">{metric}</td>
                            {d.weekOverWeek.map((v, wi) => (
                              <td key={wi} className="py-1.5 px-2 text-center text-slate-600">
                                {v > 0 ? v : <span className="text-slate-300">—</span>}
                              </td>
                            ))}
                            <td className="py-1.5 px-2 text-center font-semibold">
                              {d.average > 0 ? d.average : <span className="text-slate-300">—</span>}
                            </td>
                            <td className="py-1.5 pl-2 text-sm">
                              <TrendArrow trend={d.trend} />{" "}
                              <span className="text-xs capitalize text-slate-500">{d.trend}</span>
                            </td>
                          </tr>
                        );
                      })}
                    </tbody>
                  </table>
                </div>
                {report.trends.stool.normalDays + report.trends.stool.abnormalDays > 0 && (
                  <p className="text-xs text-slate-500 mt-2">
                    Gut/stool: {report.trends.stool.normalDays} normal days, {report.trends.stool.abnormalDays} abnormal days.
                  </p>
                )}
              </Section>

              {/* Flagged concerns */}
              <Section title={`Flagged Concerns (${report.concerns.length})`}>
                {report.concerns.length === 0 ? (
                  <p className="text-sm text-green-700 font-medium">
                    ✓ No concerning patterns detected in the 30-day window.
                  </p>
                ) : (
                  <div className="space-y-2">
                    {report.concerns.map((concern, i) => (
                      <div key={i} className="flex gap-2.5">
                        <SeverityDot severity={concern.severity} />
                        <div className="min-w-0">
                          <div className="flex items-center gap-1.5 flex-wrap">
                            <span className="text-sm font-semibold">{concern.category}</span>
                            <span
                              className={`text-[10px] font-bold uppercase px-1.5 py-0.5 rounded ${
                                concern.severity === "high"
                                  ? "bg-red-100 text-red-700"
                                  : concern.severity === "medium"
                                  ? "bg-amber-100 text-amber-700"
                                  : "bg-slate-100 text-slate-600"
                              }`}
                            >
                              {concern.severity}
                            </span>
                          </div>
                          <p className="text-xs text-slate-600 leading-snug mt-0.5">{concern.description}</p>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </Section>

              {/* Discussion topics */}
              {report.discussionTopics.length > 0 && (
                <Section title="Recommended Discussion Topics">
                  <ol className="space-y-1.5 list-none">
                    {report.discussionTopics.map((topic, i) => (
                      <li key={i} className="flex gap-2 text-sm">
                        <span className="font-bold text-blue-700 shrink-0">{i + 1}.</span>
                        <span className="text-slate-700 leading-snug">{topic}</span>
                      </li>
                    ))}
                  </ol>
                </Section>
              )}

              {/* Weekly check-ins */}
              <Section title="Weekly Check-In Summary">
                <div className="text-sm text-slate-700 space-y-0.5">
                  <p>
                    {report.weeklyCheckIns.completed} of {report.weeklyCheckIns.totalPossible} weekly check-ins completed.
                    {report.weeklyCheckIns.vetVisitsReported > 0 && (
                      <> {report.weeklyCheckIns.vetVisitsReported} vet visit(s) reported.</>
                    )}
                  </p>
                  {report.weeklyCheckIns.newSymptomsReported && report.weeklyCheckIns.symptomDetails.length > 0 && (
                    <p className="text-xs text-slate-500">
                      New symptoms noted: {report.weeklyCheckIns.symptomDetails.join("; ")}
                    </p>
                  )}
                  {!report.weeklyCheckIns.newSymptomsReported && (
                    <p className="text-xs text-slate-500">No new symptoms reported in weekly check-ins.</p>
                  )}
                </div>
              </Section>

              {/* Supplements / meds */}
              <Section title="Current Medications & Supplements">
                {report.supplements.length === 0 ? (
                  <p className="text-sm text-slate-500">None recorded.</p>
                ) : (
                  <div className="grid grid-cols-2 gap-1">
                    {report.supplements.map((s, i) => (
                      <div key={i} className="text-xs text-slate-700">
                        • {s.name} ({s.dosage})
                      </div>
                    ))}
                  </div>
                )}
              </Section>

              {/* Alert history */}
              {report.alerts.length > 0 && (
                <Section title="Recent Health Alerts (30 days)">
                  <div className="space-y-1">
                    {report.alerts.slice(0, 5).map((alert, i) => (
                      <div key={i} className="flex items-start gap-2 text-xs text-slate-600">
                        <span
                          className={`font-bold shrink-0 ${
                            alert.level === "red"
                              ? "text-red-600"
                              : alert.level === "yellow"
                              ? "text-amber-600"
                              : "text-green-600"
                          }`}
                        >
                          [{alert.level.toUpperCase()}]
                        </span>
                        <span>{alert.date}</span>
                        <span className="text-slate-500 truncate">{alert.reason}</span>
                      </div>
                    ))}
                  </div>
                </Section>
              )}

            </div>
          </div>

          {/* Footer */}
          <p className="text-center text-xs text-slate-400 pb-4">
            Generated by{" "}
            <a href="https://fursbliss.com" className="underline">
              FursBliss
            </a>{" "}
            · This report reflects owner-recorded observations only. It is not a veterinary
            diagnosis. Discuss all findings with your veterinarian. Report expires{" "}
            {record.expiresAt.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}.
          </p>
        </div>
      </div>
    </>
  );
}
