#!/usr/bin/env python3
"""
Publish due social queue items to Instagram + Facebook.

Queue format: openclaw_social_queue.json generated by openclaw_social_cron.py
Safe behavior:
  - posts only items scheduled at or before now
  - posts each item once (state tracking)
  - handles platform filtering from item.platforms
"""

from __future__ import annotations

import argparse
import json
import os
from datetime import datetime
from pathlib import Path
from typing import Dict, List

import requests

META_API_VERSION = "v18.0"
GRAPH_URL = f"https://graph.facebook.com/{META_API_VERSION}"


def load_env() -> None:
    env_files = [
        Path("/Users/ladmin/.env.fursbliss"),
        Path("/Users/ladmin/fursbliss_growth/.env"),
        Path("/Volumes/Macintosh HD-1/Users/ladmin/.env.fursbliss"),
        Path("/Volumes/Macintosh HD-1/Users/ladmin/fursbliss_growth/.env"),
    ]
    for env_file in env_files:
        if not env_file.exists():
            continue
        for raw_line in env_file.read_text(encoding="utf-8").splitlines():
            line = raw_line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            key = key.strip().removeprefix("export ").strip()
            os.environ[key] = value.strip()


def parse_local_datetime(value: str) -> datetime:
    return datetime.strptime(value, "%Y-%m-%d %H:%M")


def get_page_token(page_id: str, access_token: str) -> str | None:
    response = requests.get(
        f"{GRAPH_URL}/{page_id}",
        params={"fields": "access_token", "access_token": access_token},
        timeout=20,
    )
    if response.status_code != 200:
        return None
    return response.json().get("access_token")


def post_instagram(ig_account_id: str, access_token: str, caption: str, image_url: str) -> bool:
    media = requests.post(
        f"{GRAPH_URL}/{ig_account_id}/media",
        data={"image_url": image_url, "caption": caption, "access_token": access_token},
        timeout=30,
    )
    if media.status_code not in (200, 201):
        return False
    creation_id = media.json().get("id")
    if not creation_id:
        return False

    publish = requests.post(
        f"{GRAPH_URL}/{ig_account_id}/media_publish",
        data={"creation_id": creation_id, "access_token": access_token},
        timeout=30,
    )
    return publish.status_code in (200, 201)


def post_facebook(page_id: str, page_token: str, message: str, link: str, image_url: str) -> bool:
    payload = {
        "message": message,
        "link": link,
        "picture": image_url,
        "access_token": page_token,
    }
    response = requests.post(f"{GRAPH_URL}/{page_id}/feed", data=payload, timeout=25)
    return response.status_code in (200, 201)


def main() -> None:
    parser = argparse.ArgumentParser(description="Auto-post due queue items to Meta/Instagram.")
    parser.add_argument(
        "--queue-file",
        default="/Users/ladmin/fursbliss_growth/openclaw_social/openclaw_social_queue.json",
        help="Path to social queue JSON.",
    )
    parser.add_argument(
        "--state-file",
        default="/Users/ladmin/fursbliss_growth/openclaw_social/meta_ig_state.json",
        help="Path to state file used for de-duplication.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print due items but do not publish.",
    )
    args = parser.parse_args()

    load_env()
    meta_token = os.getenv("META_ACCESS_TOKEN") or os.getenv("FACEBOOK_ACCESS_TOKEN")
    ig_token = os.getenv("INSTAGRAM_ACCESS_TOKEN") or meta_token
    page_id = os.getenv("FACEBOOK_PAGE_ID")
    ig_account_id = os.getenv("INSTAGRAM_BUSINESS_ID")

    if not (meta_token and ig_token and page_id and ig_account_id):
        raise SystemExit("Missing required Meta/IG environment variables.")

    queue_path = Path(args.queue_file)
    state_path = Path(args.state_file)
    if not queue_path.exists():
        raise SystemExit(f"Queue file not found: {queue_path}")

    queue_data = json.loads(queue_path.read_text(encoding="utf-8"))
    items: List[Dict[str, object]] = queue_data.get("items", [])

    if state_path.exists():
        state = json.loads(state_path.read_text(encoding="utf-8"))
    else:
        state = {"posted_ids": [], "history": []}

    posted_ids = set(state.get("posted_ids", []))
    now = datetime.now()
    page_token = get_page_token(page_id, meta_token)
    if not page_token and not args.dry_run:
        raise SystemExit("Could not exchange Meta token for Facebook page token.")

    for item in items:
        item_id = f"{item.get('scheduled_local')}-{item.get('day_index')}-{item.get('day_title')}"
        if item_id in posted_ids:
            continue

        scheduled = parse_local_datetime(str(item.get("scheduled_local")))
        if scheduled > now:
            continue

        platforms = str(item.get("platforms", ""))
        caption = f"{item.get('hook_text')}\n\n{item.get('caption')}\n\n{item.get('hashtags')}"
        link = str(item.get("destination_url") or "https://www.fursbliss.com")
        image_url = str(item.get("image_url") or "https://www.fursbliss.com/og-default.jpg")

        do_ig = "Instagram" in platforms
        do_fb = "Facebook" in platforms
        ig_ok = True
        fb_ok = True

        if args.dry_run:
            print(f"[DRY RUN] Would post: {item_id} -> {platforms}")
        else:
            if do_ig:
                ig_ok = post_instagram(ig_account_id, ig_token, caption, image_url)
            if do_fb:
                fb_ok = post_facebook(page_id, page_token, caption, link, image_url)

        if ig_ok and fb_ok:
            posted_ids.add(item_id)
            state.setdefault("history", []).append(
                {
                    "item_id": item_id,
                    "posted_at": datetime.now().isoformat(),
                    "platforms": platforms,
                }
            )

    state["posted_ids"] = sorted(posted_ids)
    state_path.parent.mkdir(parents=True, exist_ok=True)
    state_path.write_text(json.dumps(state, indent=2), encoding="utf-8")
    print(f"Updated state: {state_path}")


if __name__ == "__main__":
    main()
